apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-image-webhook
  namespace: admission-controller
webhooks:
  - name: image-abriment.admission-controller.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    namespaceSelector:
      matchLabels:
        abriment/mutating-webhooks: 'enabled'    
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
          - "statefulsets"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: image-abriment
        namespace: admission-controller
        path: /mutate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3VENDQXRXZ0F3SUJBZ0lVVTgzV0dnaE9PNXpnVnE3dXBIdE9nK2d3akM0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdNQ0Vsc2JHbHViMmx6TVJBd0RnWURWUVFIREFkRAphR2xqWVdkdk1SRXdEd1lEVlFRS0RBaEJZbkpwYldWdWRERWtNQ0lHQTFVRUF3d2JRV0p5YVcxbGJuUWdRMjl1CmRISnZiR3hsY2lCWFpXSm9iMjlyTUI0WERUSXpNVEV5TVRFM01UTTBNVm9YRFRJMk1Ea3hNREUzTVRNME1Wb3cKYXpFTE1Ba0dBMVVFQmhNQ1ZWTXhFVEFQQmdOVkJBZ01DRWxzYkdsdWIybHpNUkF3RGdZRFZRUUhEQWREYUdsagpZV2R2TVJFd0R3WURWUVFLREFoQlluSnBiV1Z1ZERFa01DSUdBMVVFQXd3YlFXSnlhVzFsYm5RZ1EyOXVkSEp2CmJHeGxjaUJYWldKb2IyOXJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVDRWIKZ2dlSzBKd3l2WEM2dVJXMnJUSWhLZDVEbXlLRlR1ZTlaQVdXSm5PZFhaZW5hVjhjSmJNRXJRMXdlMHhjMVFVbQpYYjJBRTJheTVQWllHdlJBd1Z5RHNFZEttY0YwakhmYyt2UzBKcHJmTjA3UFhRYmphTWpXaHAwdTRJbnVRejhuCnhlNm50bDc0WkNSZWhOa0pnQ2hsU1JvbFhRUW1FTjl3MVZJTUtWencxY01qNWs2OHZBVXVGemZ4Ri9lQlkzZ0EKMWZMR1N4bk1tYU8rQnY3NHFlQ1B0TGx1WlZNRExwQng2K3l6bGhXd25sK09Ob3p6YlhwTGxmWU5BY0xxUTJ5RQo2bmphbHg5Ulc3aVY3eXdJT3BlVHd6NEFFVGVZcUNwTzNpQWlITWNMSTRyeGI3RTg4T0M2dFNKMXBMbi9JdjgxCnVxaHRFOGJqWEkwMktPS0hjUUlEQVFBQm80R0lNSUdGTUIwR0ExVWREZ1FXQkJTMlVGdnJWdklBTkRLcVFmSXcKYmNtM2FTd1ZmREFmQmdOVkhTTUVHREFXZ0JTMlVGdnJWdklBTkRLcVFmSXdiY20zYVN3VmZEQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NRElHQTFVZEVRUXJNQ21DSjJsdFlXZGxMV0ZpY21sdFpXNTBMbUZrYldsemMybHZiaTFqCmIyNTBjbTlzYkdWeUxuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb1pOMVJpdzlVRXVVVURmQWxoODIKMHZyNnFkbWNVYkl6Rk5IN3ZzbnVHWWFNVjF1SkRuWkg3S3NZaUpaaDUvejZUN2h6MzVoNC96ZTl5cEFrTktaUgpyQ0Z6djhzSHpLcUpENnEwU016ZmVaNGVIUytOL1dDbFhnOGNLNElPK2J0VlRaWnBlVC9MYncxTTNEbG1PdHZuCjRpUzVKZ0xxT2M4ZjdTM2dQT2doUVpEc2VQamY2bzZxWE4vcVpUaVhQc1JpRzhQY2lOUUNwT2V3RkhsV1B1d0sKMTF1SkFHODlwa2JEN0lib0hkcUg5ZHcvbi93VEhjTVVvZkpTY1pkUTFSUUNGTk4zbWYvdC9HelR1WURJU0FRTQpVT21VemJnYklRMjRCRXMvYjRLRW9XRHBoM2I0REt4V01pZWw4NVZjdmtZSkNGZDRWZDZWWVVQRFBvZ085UnQrCmdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=